#!/bin/sh

if [ "$1" != "configure" ]; then
  exit 1
fi

if [ -x "/etc/init.d/nomnomlog" ]; then
  update-rc.d nomnomlog defaults >/dev/null
 
  if [ -n "$2" ]; then
    # Upgrade
    invoke-rc.d nomnomlog restart
  fi
fi

