PACKAGE_NAME := nomnomlog
PACKAGE_VENDOR := "Shadowbq-Fork"
PACKAGE_LICENSE := "MIT License"
PACKAGE_CONTACT := shadowbq@gmail.com
PACKAGE_DESCRIPTION := "Lightweight self-contained daemon for reading local files and emitting remote syslog (without using local syslog daemon)"
PACKAGE_URL := https://github.com/shadowbq/nomnomlog
PACKAGE_VERSION := $(shell cat VERSION)